# Generated by Django 5.1.6 on 2025-02-10 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер стола')),
                ('items', models.JSONField(help_text='Формат: [{"name": "Блюдо", "price": 100}]', verbose_name='Список блюд')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('ready', 'Готово'), ('paid', 'Оплачено')], default='pending', max_length=10, verbose_name='Статус заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
