# Generated by Django 5.1.6 on 2025-02-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.JSONField(default=list, help_text='Формат: [{"name": "Блюдо", "price": 100, "quantity": 1}]', verbose_name='Список блюд'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
